name: Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: powershell

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt-get install cppcheck
    - name: analyse
      run: cppcheck --enableall 3_Implementations
   
